### ISSUE TITLE
Podezření že AppTree.count_finished_nodes je blbě (Pepo?)

### ISSUE THREAD

**Issue by tomkren** [tomkren/TFGPy#6]
počítá se to:
```
counts[App] + counts[Leaf] - counts[UnfinishedLeaf]
```
... ale to se mi zda blbě, myslim že má bejt:
```
counts[App] + counts[Leaf]
```
Dobře by to bylo, pokud by UnfinishedLeaf zvěčil počet jak Leaf, tak UnfinishedLeaf, jenže ten dle defaultní implementace zvěčí akorat `type(self)`, což je imho UnfinishedLeaf, tedy neni třeba odčítat.

Vůbec byto chtelo tydle county zrevidovat a ujednotit. (Psal je Pepa bez mýho čeku a ja tam v tu dobu psal paralelně ve svý větvi nějaký svoje počítáčky, který se s těma Pep_countama krejou.)

**Comment by jmoudrik** [comment]
Pockej, tohle uz sme opravovali! Neprimergoval si tam nejakou starou verzi??

Dne ne 2. 7. 2017 16:53 uživatel Tomáš Křen <notifications@github.com>
napsal:

**Comment by tomkren** [comment]
nic jsem nemargoval, ale asi jsem se forknul dřív než jsme to u tebe opravili

**Comment by tomkren** [comment]
jo, v tom nově mergnutym je to už opravený
